FROM davecoulter/yse_pz_web:latest
LABEL description="Ubuntu image for YSEPZ"
LABEL maintainer="Dave Coulter (dcoulter@ucsc.edu)"

SHELL ["/bin/bash", "-c"]

RUN apt-get update --fix-missing && \
apt-get install -y python3-pip && \
pip install --upgrade pip

WORKDIR /app

COPY requirements.web.dev /app/requirements.web.txt
RUN pip install -r /app/requirements.web.txt

RUN apt-get clean && \
rm -rf /var/lib/apt/lists/*
