FROM ubuntu:focal-20210723
#FROM davecoulter/ysepz_test:4.0
LABEL description="Ubuntu image for YSEPZ"
LABEL maintainer="Dave Coulter (dcoulter@ucsc.edu)"

SHELL ["/bin/bash", "-c"]

RUN apt-get update --fix-missing && \
apt-get install -y tzdata && \
apt-get install -y build-essential checkinstall && \
apt-get install -y libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev  && \
apt-get install -y python3.8 && \
apt-get install -y python3-pip && \
pip install --upgrade pip

RUN apt-get install -y libmysqlclient-dev

WORKDIR /app

# Package manifests. HACK: broken into layers to get conflicting installs working
#COPY requirements_numpy.txt /app/requirements_test.txt
#COPY requirements_20210819.txt /app/requirements.txt
#COPY requirements_20220204_bridge.txt /app/requirements_20220204_bridge.txt
#COPY requirements_20220204_bridge2.txt /app/requirements_20220204_bridge2.txt
#COPY requirements_20220204_bridge3.txt /app/requirements_20220204_bridge3.txt
COPY requirements_1.txt /app/requirements_1.txt
COPY requirements_2.txt /app/requirements_2.txt
COPY requirements_3.txt /app/requirements_3.txt
COPY requirements_4.txt /app/requirements_4.txt
COPY requirements_5.txt /app/requirements_5.txt

# HACK: install in layers to get conflicting installs working
#RUN pip install -r requirements_test.txt
#RUN pip install -r requirements.txt
#RUN pip install -r requirements_20220204_bridge.txt
#RUN pip install -r requirements_20220204_bridge2.txt
#RUN pip install -r requirements_20220204_bridge3.txt
RUN pip install -r requirements_1.txt
RUN pip install -r requirements_2.txt
RUN pip install -r requirements_3.txt
RUN pip install -r requirements_4.txt
RUN pip install -r requirements_5.txt


# HACK: Code that was changed on production. Not ideal, but trying to recreate.
COPY ./TempCode/el_pagination/models.py /usr/local/lib/python3.8/dist-packages/el_pagination/models.py
COPY ./TempCode/el_pagination/templatetags/el_pagination_tags.py /usr/local/lib/python3.8/dist-packages/el_pagination/templatetags/el_pagination_tags.py
COPY ./TempCode/auditlog/registry.py /usr/local/lib/python3.8/dist-packages/auditlog/registry.py
COPY ./TempCode/auditlog/models.py /usr/local/lib/python3.8/dist-packages/auditlog/models.py
COPY ./TempCode/auditlog/middleware.py /usr/local/lib/python3.8/dist-packages/auditlog/middleware.py
COPY ./TempCode/auditlog/diff.py /usr/local/lib/python3.8/dist-packages/auditlog/diff.py
COPY ./TempCode/django_cron/admin.py /usr/local/lib/python3.8/dist-packages/django_cron/admin.py
COPY ./TempCode/django_cron/helpers.py /usr/local/lib/python3.8/dist-packages/django_cron/helpers.py
COPY ./TempCode/jsonfield/fields.py /usr/local/lib/python3.8/dist-packages/jsonfield/fields.py


#RUN apt-get install -y apache2

# NEW packages
#COPY requirements_numpy.txt /app/requirements_numpy.txt
#COPY requirements_20220118.txt /app/requirements.txt
#COPY requirements_bokeh.txt /app/requirements_bokeh.txt
#COPY requirements_auditlog.txt /app/requirements_auditlog.txt
#RUN pip install -r requirements_numpy.txt
#RUN pip install -r requirements.txt
#RUN pip install -r requirements_bokeh.txt
#RUN pip install -r requirements_auditlog.txt


RUN apt-get clean && \
rm -rf /var/lib/apt/lists/*