FROM ghcr.io/davecoulter/yse_pz:latest
LABEL description="Ubuntu image for YSEPZ"
LABEL maintainer="Dave Coulter (dcoulter@ucsc.edu)"

SHELL ["/bin/bash", "-c"]

RUN apt-get update --fix-missing && \
pip install --upgrade pip

WORKDIR /app
RUN mkdir -p /app/ghost_logs

COPY requirements.web.dev /app/requirements.web.txt
RUN pip install -r /app/requirements.web.txt

RUN apt-get clean && \
rm -rf /var/lib/apt/lists/*
