from django.contrib import admin

# Register your models here.
from .models import *

admin.site.register(TransientHostRank)
admin.site.register(Status)
admin.site.register(ObservationGroup)
admin.site.register(SEDType)
admin.site.register(HostMorphology)
admin.site.register(Phase)
admin.site.register(TransientClass)
admin.site.register(HostClass)
admin.site.register(Observatory)
admin.site.register(Telescope)
admin.site.register(Instrument)
admin.site.register(ToO_Resource)
admin.site.register(Classical_Resource)
admin.site.register(Queued_Resource)
admin.site.register(ClassicalObservingDate)
admin.site.register(QueuedObservingDate)
admin.site.register(InstrumentConfig)
admin.site.register(ConfigElement)
admin.site.register(PhotometricBand)
admin.site.register(Host)
admin.site.register(Transient)
admin.site.register(Followup)
admin.site.register(ObservationTask)
admin.site.register(Spectrum)
admin.site.register(Photometry)
admin.site.register(InformationSource)
admin.site.register(WebResource)
admin.site.register(AlternateTransientNames)
admin.site.register(SpecData)
admin.site.register(PhotData)
admin.site.register(Image)
admin.site.register(HostSED)
admin.site.register(Log)