# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateTransientNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatetransientnames_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatetransientnames_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassicalNightType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classicalnighttype_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classicalnighttype_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassicalObservingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('obs_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classicalobservingdate_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classicalobservingdate_modified_by', to=settings.AUTH_USER_MODEL)),
                ('night_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.ClassicalNightType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassicalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('begin_date_valid', models.DateTimeField()),
                ('end_date_valid', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classicalresource_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classicalresource_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configelement_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('redshift', models.FloatField(blank=True, null=True)),
                ('redshift_err', models.FloatField(blank=True, null=True)),
                ('r_a', models.FloatField(blank=True, null=True)),
                ('r_b', models.FloatField(blank=True, null=True)),
                ('theta', models.FloatField(blank=True, null=True)),
                ('eff_offset', models.FloatField(blank=True, null=True)),
                ('photo_z', models.FloatField(blank=True, null=True)),
                ('photo_z_err', models.FloatField(blank=True, null=True)),
                ('photo_z_source', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostclass_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostclass_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostFollowup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('valid_start', models.DateTimeField()),
                ('valid_stop', models.DateTimeField()),
                ('spec_priority', models.IntegerField(blank=True, null=True)),
                ('phot_priority', models.IntegerField(blank=True, null=True)),
                ('offset_star_ra', models.FloatField(blank=True, null=True)),
                ('offset_star_dec', models.FloatField(blank=True, null=True)),
                ('offset_north', models.FloatField(blank=True, null=True)),
                ('offset_east', models.FloatField(blank=True, null=True)),
                ('classical_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.ClassicalResource')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostfollowup_created_by', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Host')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostfollowup_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostMorphology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostmorphology_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostmorphology_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostObservationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('exposure_time', models.FloatField()),
                ('number_of_exposures', models.IntegerField()),
                ('desired_obs_date', models.DateTimeField()),
                ('actual_obs_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostobservationtask_created_by', to=settings.AUTH_USER_MODEL)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostFollowup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostSED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('metalicity', models.FloatField(blank=True, null=True)),
                ('metalicity_err', models.FloatField(blank=True, null=True)),
                ('log_SFR', models.FloatField(blank=True, null=True)),
                ('log_SFR_err', models.FloatField(blank=True, null=True)),
                ('log_sSFR', models.FloatField(blank=True, null=True)),
                ('log_sSFR_err', models.FloatField(blank=True, null=True)),
                ('log_mass', models.FloatField(blank=True, null=True)),
                ('log_mass_err', models.FloatField(blank=True, null=True)),
                ('ebv', models.FloatField(blank=True, null=True)),
                ('ebv_err', models.FloatField(blank=True, null=True)),
                ('log_age', models.FloatField(blank=True, null=True)),
                ('log_age_err', models.FloatField(blank=True, null=True)),
                ('redshift', models.FloatField(blank=True, null=True)),
                ('redshift_err', models.FloatField(blank=True, null=True)),
                ('fit_chi2', models.FloatField(blank=True, null=True)),
                ('fit_n', models.IntegerField(blank=True, null=True)),
                ('fit_plot_file', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostsed_created_by', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Host')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostsed_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostSpectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('obs_date', models.DateTimeField()),
                ('redshift', models.FloatField(blank=True, null=True)),
                ('redshift_err', models.FloatField(blank=True, null=True)),
                ('redshift_quality', models.NullBooleanField()),
                ('tdr', models.FloatField(blank=True, null=True)),
                ('spec_plot_file', models.CharField(blank=True, max_length=512, null=True)),
                ('spec_data_file', models.CharField(blank=True, max_length=512, null=True)),
                ('spectrum_notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostspectrum_created_by', to=settings.AUTH_USER_MODEL)),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostFollowup')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Host')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('img_file', models.CharField(blank=True, max_length=512, null=True)),
                ('zero_point', models.FloatField(blank=True, null=True)),
                ('zero_point_err', models.FloatField(blank=True, null=True)),
                ('sky', models.FloatField(blank=True, null=True)),
                ('sky_rms', models.FloatField(blank=True, null=True)),
                ('dcmp_file', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informationsource_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informationsource_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentconfig_created_by', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Instrument')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentconfig_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('config_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.ConfigElement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_created_by', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Host')),
                ('host_followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostFollowup')),
                ('host_observation_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostObservationTask')),
                ('host_sed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostSED')),
                ('host_spectrum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostSpectrum')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Instrument')),
                ('instrument_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.InstrumentConfig')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObservationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observationgroup_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observationgroup_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('utc_offset', models.IntegerField()),
                ('tz_name', models.CharField(max_length=64)),
                ('DLS_utc_offset', models.IntegerField(blank=True, null=True)),
                ('DLS_tz_name', models.CharField(blank=True, max_length=64, null=True)),
                ('DLS_start', models.DateTimeField(blank=True, null=True)),
                ('DLS_end', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observatory_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observatory_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('obs_date', models.DateTimeField()),
                ('flux_zero_point', models.FloatField(blank=True, null=True)),
                ('flux', models.FloatField(blank=True, null=True)),
                ('flux_err', models.FloatField(blank=True, null=True)),
                ('mag', models.FloatField(blank=True, null=True)),
                ('mag_err', models.FloatField(blank=True, null=True)),
                ('forced', models.NullBooleanField()),
                ('dq', models.NullBooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotometricBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('lambda_eff', models.CharField(max_length=64)),
                ('throughput_file', models.CharField(blank=True, max_length=512, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photometricband_created_by', to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Instrument')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photometricband_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueuedResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('begin_date_valid', models.DateTimeField()),
                ('end_date_valid', models.DateTimeField()),
                ('awarded_hours', models.FloatField(blank=True, null=True)),
                ('used_hours', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queuedresource_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queuedresource_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEDType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedtype_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedtype_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('wavelength', models.FloatField()),
                ('flux', models.FloatField()),
                ('wavelength_err', models.FloatField(blank=True, null=True)),
                ('flux_err', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telescope_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telescope_modified_by', to=settings.AUTH_USER_MODEL)),
                ('observatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Observatory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToOResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('begin_date_valid', models.DateTimeField()),
                ('end_date_valid', models.DateTimeField()),
                ('awarded_too_hours', models.FloatField()),
                ('used_too_hours', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooresource_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooresource_modified_by', to=settings.AUTH_USER_MODEL)),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Telescope')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('disc_date', models.DateTimeField()),
                ('redshift', models.FloatField(blank=True, null=True)),
                ('redshift_err', models.FloatField(blank=True, null=True)),
                ('redshift_source', models.CharField(blank=True, max_length=64, null=True)),
                ('non_detect_date', models.DateTimeField(blank=True, null=True)),
                ('non_detect_limit', models.FloatField(blank=True, null=True)),
                ('mw_ebv', models.FloatField(blank=True, null=True)),
                ('abs_mag_peak', models.FloatField(blank=True, null=True)),
                ('abs_mag_peak_date', models.DateTimeField(blank=True, null=True)),
                ('postage_stamp_file', models.CharField(blank=True, max_length=512, null=True)),
                ('abs_mag_peak_band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='YSE_App.PhotometricBand')),
                ('best_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='YSE_App.Host')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransientClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transientclass_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transientclass_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransientFollowup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('valid_start', models.DateTimeField()),
                ('valid_stop', models.DateTimeField()),
                ('spec_priority', models.IntegerField(blank=True, null=True)),
                ('phot_priority', models.IntegerField(blank=True, null=True)),
                ('offset_star_ra', models.FloatField(blank=True, null=True)),
                ('offset_star_dec', models.FloatField(blank=True, null=True)),
                ('offset_north', models.FloatField(blank=True, null=True)),
                ('offset_east', models.FloatField(blank=True, null=True)),
                ('classical_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.ClassicalResource')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transientfollowup_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transientfollowup_modified_by', to=settings.AUTH_USER_MODEL)),
                ('queued_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.QueuedResource')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Status')),
                ('too_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.ToOResource')),
                ('transient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Transient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransientHostRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transienthostrank_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transienthostrank_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransientObservationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('exposure_time', models.FloatField()),
                ('number_of_exposures', models.IntegerField()),
                ('desired_obs_date', models.DateTimeField()),
                ('actual_obs_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transientobservationtask_created_by', to=settings.AUTH_USER_MODEL)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientFollowup')),
                ('instrument_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.InstrumentConfig')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transientobservationtask_modified_by', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransientSpectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('obs_date', models.DateTimeField()),
                ('redshift', models.FloatField(blank=True, null=True)),
                ('redshift_err', models.FloatField(blank=True, null=True)),
                ('redshift_quality', models.NullBooleanField()),
                ('tdr', models.FloatField(blank=True, null=True)),
                ('spec_plot_file', models.CharField(blank=True, max_length=512, null=True)),
                ('spec_data_file', models.CharField(blank=True, max_length=512, null=True)),
                ('spectrum_notes', models.TextField(blank=True, null=True)),
                ('snid_plot_file', models.CharField(blank=True, max_length=512, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transientspectrum_created_by', to=settings.AUTH_USER_MODEL)),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientFollowup')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Instrument')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transientspectrum_modified_by', to=settings.AUTH_USER_MODEL)),
                ('obs_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.ObservationGroup')),
                ('spec_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Phase')),
                ('transient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Transient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('information_text', models.TextField()),
                ('url', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='YSE_App.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('YSE_App.image',),
        ),
        migrations.CreateModel(
            name='HostPhotData',
            fields=[
                ('photdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='YSE_App.PhotData')),
            ],
            options={
                'abstract': False,
            },
            bases=('YSE_App.photdata',),
        ),
        migrations.CreateModel(
            name='HostPhotometry',
            fields=[
                ('photometry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='YSE_App.Photometry')),
            ],
            options={
                'abstract': False,
            },
            bases=('YSE_App.photometry',),
        ),
        migrations.CreateModel(
            name='HostSpecData',
            fields=[
                ('specdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='YSE_App.SpecData')),
            ],
            options={
                'abstract': False,
            },
            bases=('YSE_App.specdata',),
        ),
        migrations.CreateModel(
            name='HostWebResource',
            fields=[
                ('webresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='YSE_App.WebResource')),
            ],
            options={
                'abstract': False,
            },
            bases=('YSE_App.webresource',),
        ),
        migrations.CreateModel(
            name='TransientImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='YSE_App.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('YSE_App.image',),
        ),
        migrations.CreateModel(
            name='TransientPhotData',
            fields=[
                ('photdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='YSE_App.PhotData')),
            ],
            options={
                'abstract': False,
            },
            bases=('YSE_App.photdata',),
        ),
        migrations.CreateModel(
            name='TransientPhotometry',
            fields=[
                ('photometry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='YSE_App.Photometry')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientFollowup')),
            ],
            options={
                'abstract': False,
            },
            bases=('YSE_App.photometry',),
        ),
        migrations.CreateModel(
            name='TransientSpecData',
            fields=[
                ('specdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='YSE_App.SpecData')),
                ('spectrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientSpectrum')),
            ],
            options={
                'abstract': False,
            },
            bases=('YSE_App.specdata',),
        ),
        migrations.CreateModel(
            name='TransientWebResource',
            fields=[
                ('webresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='YSE_App.WebResource')),
            ],
            options={
                'abstract': False,
            },
            bases=('YSE_App.webresource',),
        ),
        migrations.AddField(
            model_name='webresource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webresource_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webresource',
            name='information_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.InformationSource'),
        ),
        migrations.AddField(
            model_name='webresource',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webresource_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transient',
            name='best_spec_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='YSE_App.TransientClass'),
        ),
        migrations.AddField(
            model_name='transient',
            name='best_spectrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='YSE_App.TransientSpectrum'),
        ),
        migrations.AddField(
            model_name='transient',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transient_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transient',
            name='host',
            field=models.ManyToManyField(blank=True, to='YSE_App.Host'),
        ),
        migrations.AddField(
            model_name='transient',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transient_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transient',
            name='non_detect_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='YSE_App.PhotometricBand'),
        ),
        migrations.AddField(
            model_name='transient',
            name='obs_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.ObservationGroup'),
        ),
        migrations.AddField(
            model_name='transient',
            name='photo_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='YSE_App.TransientClass'),
        ),
        migrations.AddField(
            model_name='transient',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Status'),
        ),
        migrations.AddField(
            model_name='specdata',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specdata_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specdata',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specdata_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queuedresource',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Telescope'),
        ),
        migrations.AddField(
            model_name='photometry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photometry_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photometry',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Instrument'),
        ),
        migrations.AddField(
            model_name='photometry',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photometry_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photometry',
            name='obs_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.ObservationGroup'),
        ),
        migrations.AddField(
            model_name='photdata',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.PhotometricBand'),
        ),
        migrations.AddField(
            model_name='photdata',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photdata_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photdata',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photdata_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='log',
            name='transient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Transient'),
        ),
        migrations.AddField(
            model_name='log',
            name='transient_followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientFollowup'),
        ),
        migrations.AddField(
            model_name='log',
            name='transient_observation_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientObservationTask'),
        ),
        migrations.AddField(
            model_name='log',
            name='transient_spectrum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientSpectrum'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Telescope'),
        ),
        migrations.AddField(
            model_name='image',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostspectrum',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Instrument'),
        ),
        migrations.AddField(
            model_name='hostspectrum',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostspectrum_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostspectrum',
            name='obs_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.ObservationGroup'),
        ),
        migrations.AddField(
            model_name='hostsed',
            name='sed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.SEDType'),
        ),
        migrations.AddField(
            model_name='hostobservationtask',
            name='instrument_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.InstrumentConfig'),
        ),
        migrations.AddField(
            model_name='hostobservationtask',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostobservationtask_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostobservationtask',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Status'),
        ),
        migrations.AddField(
            model_name='hostfollowup',
            name='queued_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.QueuedResource'),
        ),
        migrations.AddField(
            model_name='hostfollowup',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Status'),
        ),
        migrations.AddField(
            model_name='hostfollowup',
            name='too_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.ToOResource'),
        ),
        migrations.AddField(
            model_name='host',
            name='band_sextract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.PhotometricBand'),
        ),
        migrations.AddField(
            model_name='host',
            name='best_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='YSE_App.HostSpectrum'),
        ),
        migrations.AddField(
            model_name='host',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='host',
            name='host_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostClass'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_morphology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostMorphology'),
        ),
        migrations.AddField(
            model_name='host',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='host',
            name='transient_host_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientHostRank'),
        ),
        migrations.AddField(
            model_name='configelement',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Instrument'),
        ),
        migrations.AddField(
            model_name='configelement',
            name='instrument_config',
            field=models.ManyToManyField(blank=True, to='YSE_App.InstrumentConfig'),
        ),
        migrations.AddField(
            model_name='configelement',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configelement_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classicalresource',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Telescope'),
        ),
        migrations.AddField(
            model_name='classicalobservingdate',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.ClassicalResource'),
        ),
        migrations.AddField(
            model_name='alternatetransientnames',
            name='obs_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.ObservationGroup'),
        ),
        migrations.AddField(
            model_name='alternatetransientnames',
            name='transient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Transient'),
        ),
        migrations.AddField(
            model_name='transientwebresource',
            name='transient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Transient'),
        ),
        migrations.AddField(
            model_name='transientphotometry',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Host'),
        ),
        migrations.AddField(
            model_name='transientphotometry',
            name='transient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Transient'),
        ),
        migrations.AddField(
            model_name='transientphotdata',
            name='photometry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientPhotometry'),
        ),
        migrations.AddField(
            model_name='transientimage',
            name='phot_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientPhotData'),
        ),
        migrations.AddField(
            model_name='log',
            name='host_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostImage'),
        ),
        migrations.AddField(
            model_name='log',
            name='host_photometry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostPhotometry'),
        ),
        migrations.AddField(
            model_name='log',
            name='host_web_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostWebResource'),
        ),
        migrations.AddField(
            model_name='log',
            name='transient_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientImage'),
        ),
        migrations.AddField(
            model_name='log',
            name='transient_photometry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientPhotometry'),
        ),
        migrations.AddField(
            model_name='log',
            name='transient_web_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.TransientWebResource'),
        ),
        migrations.AddField(
            model_name='hostwebresource',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Host'),
        ),
        migrations.AddField(
            model_name='hostspecdata',
            name='spectrum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostSpectrum'),
        ),
        migrations.AddField(
            model_name='hostphotometry',
            name='followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostFollowup'),
        ),
        migrations.AddField(
            model_name='hostphotometry',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Host'),
        ),
        migrations.AddField(
            model_name='hostphotdata',
            name='photometry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostPhotometry'),
        ),
        migrations.AddField(
            model_name='hostimage',
            name='phot_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.HostPhotData'),
        ),
    ]
