# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
