# Generated by Django 4.0.3 on 2022-05-20 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YSE_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostspectrum',
            name='reference',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transientspectrum',
            name='reference',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transienttag',
            name='associated_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='hostphotdata',
            name='data_quality',
        ),
        migrations.AddField(
            model_name='hostphotdata',
            name='data_quality',
            field=models.ManyToManyField(blank=True, to='YSE_App.dataquality'),
        ),
        migrations.RemoveField(
            model_name='hostspectrum',
            name='data_quality',
        ),
        migrations.AddField(
            model_name='hostspectrum',
            name='data_quality',
            field=models.ManyToManyField(blank=True, to='YSE_App.dataquality'),
        ),
        migrations.RemoveField(
            model_name='transientphotdata',
            name='data_quality',
        ),
        migrations.AddField(
            model_name='transientphotdata',
            name='data_quality',
            field=models.ManyToManyField(blank=True, to='YSE_App.dataquality'),
        ),
        migrations.RemoveField(
            model_name='transientspectrum',
            name='data_quality',
        ),
        migrations.AddField(
            model_name='transientspectrum',
            name='data_quality',
            field=models.ManyToManyField(blank=True, to='YSE_App.dataquality'),
        ),
    ]
