# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transient',
            name='best_host',
        ),
        migrations.AddField(
            model_name='transient',
            name='candidate_hosts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transient',
            name='disc_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='transient',
            name='host',
        ),
        migrations.AddField(
            model_name='transient',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Host'),
        ),
    ]
