# Generated by Django 4.0.3 on 2022-08-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0002_hostspectrum_reference_transientspectrum_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyobservation',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
