# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0002_auto_20171204_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photometricband',
            name='lambda_eff',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
