# Generated by Django 4.0 on 2023-09-01 19:13

import YSE_App.models.enum_models
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('YSE_App', '0003_surveyobservation_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='FRBGalaxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('name', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(max_length=64)),
                ('redshift', models.FloatField(blank=True, null=True)),
                ('redshift_err', models.FloatField(blank=True, null=True)),
                ('ang_size', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FRBSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FRBTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.webappcolor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FRBTransient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('DM', models.FloatField()),
                ('ra_err', models.FloatField(blank=True, null=True)),
                ('dec_err', models.FloatField(blank=True, null=True)),
                ('localization_file', models.CharField(blank=True, max_length=64, null=True)),
                ('P_Ux', models.FloatField(blank=True, null=True)),
                ('redshift', models.FloatField(blank=True, null=True)),
                ('redshift_err', models.FloatField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('candidates', models.ManyToManyField(blank=True, related_name='frb_candidates', to='YSE_App.FRBGalaxy')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('frb_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.frbsurvey')),
                ('frb_tags', models.ManyToManyField(blank=True, to='YSE_App.FRBTag')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frb', to='YSE_App.frbgalaxy')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
                ('status', models.ForeignKey(on_delete=models.SET(YSE_App.models.enum_models.get_sentinel_transientstatus), to='YSE_App.transientstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transienttag',
            name='associated_users',
        ),
        migrations.AlterField(
            model_name='hostphotdata',
            name='data_quality',
            field=models.ManyToManyField(blank=True, to='YSE_App.DataQuality'),
        ),
        migrations.AlterField(
            model_name='hostspectrum',
            name='data_quality',
            field=models.ManyToManyField(blank=True, to='YSE_App.DataQuality'),
        ),
        migrations.AlterField(
            model_name='transientphotdata',
            name='data_quality',
            field=models.ManyToManyField(blank=True, to='YSE_App.DataQuality'),
        ),
        migrations.AlterField(
            model_name='transientspectrum',
            name='data_quality',
            field=models.ManyToManyField(blank=True, to='YSE_App.DataQuality'),
        ),
        migrations.AlterUniqueTogether(
            name='hostphotometry',
            unique_together={('host', 'instrument', 'obs_group')},
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('P_Ox', models.FloatField()),
                ('vetted', models.BooleanField(blank=True, default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.frbgalaxy')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
                ('transient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.frbtransient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalaxyPhotometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=512, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.frbgalaxy')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.instrument')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
                ('obs_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.observationgroup')),
            ],
            options={
                'unique_together': {('galaxy', 'instrument', 'obs_group')},
            },
        ),
        migrations.CreateModel(
            name='GalaxyPhotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('zp_off', models.FloatField(blank=True, null=True)),
                ('obs_date', models.DateTimeField()),
                ('flux_zero_point', models.FloatField(blank=True, null=True)),
                ('flux', models.FloatField(blank=True, null=True)),
                ('flux_err', models.FloatField(blank=True, null=True)),
                ('mag', models.FloatField(blank=True, null=True)),
                ('mag_err', models.FloatField(blank=True, null=True)),
                ('forced', models.BooleanField(blank=True, null=True)),
                ('diffim', models.BooleanField(blank=True, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.photometricband')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('data_quality', models.ManyToManyField(blank=True, to='YSE_App.DataQuality')),
                ('mag_sys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.magsystem')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
                ('photometry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.galaxyphotometry')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FRBTransientWebResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('information_text', models.TextField()),
                ('resource_url', models.CharField(max_length=512)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('information_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.informationsource')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
                ('transient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.frbtransient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
