# Generated by Django 4.0 on 2023-07-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0003_surveyobservation_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transienttag',
            name='associated_users',
        ),
        migrations.AlterField(
            model_name='hostphotdata',
            name='data_quality',
            field=models.ManyToManyField(blank=True, to='YSE_App.DataQuality'),
        ),
        migrations.AlterField(
            model_name='hostspectrum',
            name='data_quality',
            field=models.ManyToManyField(blank=True, to='YSE_App.DataQuality'),
        ),
        migrations.AlterField(
            model_name='transientphotdata',
            name='data_quality',
            field=models.ManyToManyField(blank=True, to='YSE_App.DataQuality'),
        ),
        migrations.AlterField(
            model_name='transientspectrum',
            name='data_quality',
            field=models.ManyToManyField(blank=True, to='YSE_App.DataQuality'),
        ),
    ]
