# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0003_auto_20171112_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternatetransientnames',
            name='transient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Transient'),
        ),
    ]
