# Generated by Django 4.0 on 2023-07-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0004_remove_transienttag_associated_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='DM',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
