# Generated by Django 4.0 on 2023-09-15 06:04

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('YSE_App', '0004_frbgalaxy_frbsurvey_frbtag_frbtransient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frbtransient',
            name='RM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frbtransient',
            name='mw_ebv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frbtransient',
            name='repeater',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='frbtransient',
            name='s2n',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FRBFollowUpResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('valid_start', models.DateTimeField()),
                ('valid_stop', models.DateTimeField()),
                ('num_targ_img', models.IntegerField()),
                ('num_targ_mask', models.IntegerField()),
                ('num_targ_longslit', models.IntegerField()),
                ('max_AM', models.FloatField()),
                ('frb_surveys', models.CharField(max_length=64)),
                ('obs_type', models.CharField(blank=True, max_length=64, null=True)),
                ('Program', models.CharField(blank=True, max_length=64, null=True)),
                ('Period', models.CharField(blank=True, max_length=64, null=True)),
                ('min_POx', models.FloatField(blank=True, null=True)),
                ('frb_tags', models.CharField(blank=True, max_length=64, null=True)),
                ('frb_statuses', models.CharField(blank=True, max_length=64, null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.principalinvestigator')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.instrument')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FRBFollowUpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.frbfollowupresource')),
                ('transient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.frbtransient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FRBFollowUpObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(max_length=64)),
                ('conditions', models.CharField(max_length=64)),
                ('texp', models.FloatField()),
                ('date', models.DateTimeField()),
                ('success', models.BooleanField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.frbfollowupresource')),
                ('transient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.frbtransient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
