# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0004_alternatetransientnames_transient'),
    ]

    operations = [
        migrations.AddField(
            model_name='observatory',
            name='daylightsavingscode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observatory',
            name='timezonename',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='observatory',
            name='utoffset',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observingnightdates',
            name='observatory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Observatory'),
        ),
    ]
