# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='k2_validated',
            field=models.NullBooleanField(),
        ),
    ]
