# Generated by Django 4.0 on 2023-10-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0005_frbtransient_rm_frbtransient_mw_ebv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frbfollowupresource',
            name='max_mag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frbfollowupresource',
            name='min_mag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frbtransient',
            name='a_err',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frbtransient',
            name='b_err',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frbtransient',
            name='theta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='YSE_App.photometricband'),
        ),
    ]
