# Generated by Django 4.0 on 2023-10-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0006_frbfollowupresource_max_mag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frbgalaxy',
            name='photoz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frbgalaxy',
            name='photoz_err',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frbgalaxy',
            name='photoz_source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='frbgalaxy',
            name='redshift_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frbgalaxy',
            name='redshift_source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='frbtransient',
            name='bright_star',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
