# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 19:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("YSE_App", "0006_transient_k2_validated")]

    operations = [
        migrations.AddField(
            model_name="transient",
            name="k2_msg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transient",
            name="internal_survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="YSE_App.InternalSurvey",
            ),
        ),
    ]
