# Generated by Django 4.0 on 2023-07-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0007_transient_p_ux_transient_candidates_alter_host_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ang_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
