# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0007_auto_20171206_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_area',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_first_three',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_last_four',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_provider_str',
            field=models.CharField(max_length=16),
        ),
    ]
