# Generated by Django 4.0 on 2023-11-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0007_frbgalaxy_photoz_frbgalaxy_photoz_err_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frbtransient',
            name='DM_ISM',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
