# Generated by Django 4.0 on 2024-03-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('YSE_App', '0008_frbtransient_dm_ism'),
    ]

    operations = [
        migrations.AddField(
            model_name='frbtransient',
            name='event_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FRBSampleCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('version', models.CharField(max_length=64)),
                ('weight', models.FloatField()),
                ('min_POx', models.FloatField()),
                ('max_EBV', models.FloatField()),
                ('max_mr', models.FloatField()),
                ('run_public_path', models.BooleanField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('stop_date', models.DateTimeField(blank=True, null=True)),
                ('max_PUx', models.FloatField(blank=True, null=True)),
                ('min_DM', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to='auth.user')),
                ('frb_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.frbsurvey')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified_by', to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
