# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 04:32
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("YSE_App", "0008_auto_20171206_2111")]

    operations = [
        migrations.AddField(
            model_name="transient",
            name="TNS_spec_class",
            field=models.CharField(blank=True, max_length=64, null=True),
        )
    ]
