# Generated by Django 4.0 on 2025-07-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0009_frbtransient_event_id_frbsamplecriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='frbsamplecriteria',
            name='apply_bright_star',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frbsamplecriteria',
            name='desc',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frbsamplecriteria',
            name='max_DM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frbsamplecriteria',
            name='max_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frbsamplecriteria',
            name='use_top_two',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
