# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("YSE_App", "0012_transient_slug")]

    operations = [migrations.RemoveField(model_name="transient", name="slug")]
