# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 05:13
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("YSE_App", "0014_transient_slug")]

    operations = [
        migrations.AlterField(
            model_name="transient",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        )
    ]
