# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("YSE_App", "0015_auto_20180215_0513"),
        ("YSE_App", "0017_auto_20180228_0258"),
    ]

    operations = []
