# Generated by Django 2.0.5 on 2018-09-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0022_photometricband_disp_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='photometricband',
            name='disp_symbol',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
