# Generated by Django 2.0.4 on 2019-01-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0024_userquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquery',
            name='name',
        ),
    ]
