# Generated by Django 2.0.4 on 2019-01-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0025_remove_userquery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorer.Query'),
        ),
    ]
