# Generated by Django 2.0.4 on 2019-03-17 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("YSE_App", "0026_auto_20190123_2029"),
    ]

    operations = [
        migrations.CreateModel(
            name="GWCandidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("field_name", models.CharField(max_length=64)),
                ("candidate_id", models.CharField(max_length=64)),
                ("alt_transient_name", models.CharField(max_length=64)),
                (
                    "websniff_url",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gwcandidate_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gwcandidate_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YSE_App.Transient",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="GWCandidateImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("image_filename", models.CharField(max_length=256)),
                ("dophot_class", models.IntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gwcandidateimage_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gw_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YSE_App.GWCandidate",
                    ),
                ),
                (
                    "image_filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YSE_App.PhotometricBand",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gwcandidateimage_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
