# Generated by Django 2.0.4 on 2019-03-18 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("YSE_App", "0027_gwcandidate_gwcandidateimage")]

    operations = [
        migrations.RenameField(
            model_name="gwcandidate", old_name="alt_transient_name", new_name="name"
        )
    ]
