# Generated by Django 2.0.4 on 2019-03-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0028_auto_20190318_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwcandidateimage',
            name='obs_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
