# Generated by Django 2.0.4 on 2019-03-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0029_gwcandidateimage_obs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='point_source_probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
