# Generated by Django 2.0.4 on 2019-06-22 03:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("YSE_App", "0030_transient_point_source_probability")]

    operations = [
        migrations.AlterField(
            model_name="transientspectrum",
            name="spec_phase",
            field=models.FloatField(blank=True, null=True),
        )
    ]
