# Generated by Django 2.0.4 on 2019-09-21 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YSE_App', '0031_auto_20190622_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTelescopeToFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usertelescopetofollow_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usertelescopetofollow_modified_by', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Profile')),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YSE_App.Telescope')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
