# Generated by Django 2.0.4 on 2019-11-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0034_alternatetransientnames_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='postage_stamp_diff',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transient',
            name='postage_stamp_ref',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
