# Generated by Django 2.0.4 on 2019-11-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0035_auto_20191106_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='postage_stamp_diff_fits',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transient',
            name='postage_stamp_file_fits',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transient',
            name='postage_stamp_ref_fits',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
