# Generated by Django 2.0.4 on 2019-11-07 00:59
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models

import YSE_App.models.enum_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("YSE_App", "0036_auto_20191106_0532"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("field_id", models.CharField(max_length=64)),
                ("first_mjd", models.FloatField(blank=True, null=True)),
                ("last_mjd", models.FloatField(blank=True, null=True)),
                ("cadence", models.FloatField(blank=True, null=True)),
                ("ra_cen", models.FloatField()),
                ("dec_cen", models.FloatField()),
                ("width_deg", models.FloatField()),
                ("height_deg", models.FloatField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveyfield_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YSE_App.Instrument",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveyfield_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obs_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YSE_App.ObservationGroup",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SurveyObservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("obs_mjd", models.FloatField(blank=True, null=True)),
                ("exposure_time", models.FloatField()),
                ("pos_angle_deg", models.FloatField()),
                ("fwhm", models.FloatField(blank=True, null=True)),
                ("eccentricity", models.FloatField(blank=True, null=True)),
                ("airmass", models.FloatField(blank=True, null=True)),
                ("image_id", models.BigIntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveyobservation_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YSE_App.Instrument",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveyobservation_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photometric_band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YSE_App.PhotometricBand",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=models.SET(
                            YSE_App.models.enum_models.get_sentinel_taskstatus
                        ),
                        to="YSE_App.TaskStatus",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SurveyObservationTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("requested_mjd", models.FloatField(blank=True, null=True)),
                ("requested_exposure_time", models.FloatField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveyobservationtask_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveyobservationtask_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_photometric_band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YSE_App.PhotometricBand",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=models.SET(
                            YSE_App.models.enum_models.get_sentinel_taskstatus
                        ),
                        to="YSE_App.TaskStatus",
                    ),
                ),
                (
                    "survey_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YSE_App.SurveyField",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="surveyobservation",
            name="survey_observation_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="YSE_App.SurveyObservationTask",
            ),
        ),
    ]
