# Generated by Django 2.0.4 on 2019-11-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0038_auto_20191107_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfield',
            name='ztf_field_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
