# Generated by Django 2.0.4 on 2019-11-24 22:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("YSE_App", "0045_yseoncalldate")]

    operations = [
        migrations.RenameField(
            model_name="surveyobservation", old_name="fwhm", new_name="fwhm_major"
        ),
        migrations.AddField(
            model_name="surveyobservation",
            name="mag_lim",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveyobservation",
            name="n_good_skycell",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveyobservation",
            name="quality",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveyobservation",
            name="zpt_obs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="surveyobservation",
            name="image_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
