# Generated by Django 2.0.4 on 2019-12-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0046_auto_20191124_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooresource',
            name='awarded_too_triggers',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tooresource',
            name='used_too_triggers',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tooresource',
            name='awarded_too_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tooresource',
            name='used_too_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
