# Generated by Django 2.0.4 on 2020-01-20 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("YSE_App", "0050_surveyfieldmsb")]

    operations = [
        migrations.RenameField(
            model_name="surveyfieldmsb",
            old_name="survey_field",
            new_name="survey_fields",
        )
    ]
