# Generated by Django 2.0.4 on 2020-03-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("YSE_App", "0051_auto_20200120_0131")]

    operations = [
        migrations.AddField(
            model_name="transient", name="has_chandra", field=models.NullBooleanField()
        ),
        migrations.AddField(
            model_name="transient", name="has_hst", field=models.NullBooleanField()
        ),
        migrations.AddField(
            model_name="transient", name="has_spitzer", field=models.NullBooleanField()
        ),
    ]
