# Generated by Django 2.0.4 on 2020-04-14 20:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("YSE_App", "0054_auto_20200413_0112")]

    operations = [
        migrations.AddField(
            model_name="surveyobservation",
            name="diff_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="surveyobservation",
            name="stack_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="surveyobservation",
            name="warp_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
