# Generated by Django 2.0.4 on 2020-04-15 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("YSE_App", "0056_auto_20200415_1656"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransientDiffImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "postage_stamp_file",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "postage_stamp_ref",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "postage_stamp_diff",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "postage_stamp_file_fits",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "postage_stamp_ref_fits",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "postage_stamp_diff_fits",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("diff_zero_point", models.FloatField(blank=True, null=True)),
                ("diff_zero_point_err", models.FloatField(blank=True, null=True)),
                ("diff_sky", models.FloatField(blank=True, null=True)),
                ("diff_sky_rms", models.FloatField(blank=True, null=True)),
                ("diff_dcmp_file", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transientdiffimage_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transientdiffimage_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phot_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YSE_App.TransientPhotData",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
