# Generated by Django 2.0.4 on 2020-04-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0057_transientdiffimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transientdiffimage',
            name='valid_pixels',
            field=models.NullBooleanField(),
        ),
    ]
