# Generated by Django 2.0.4 on 2020-05-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0058_transientdiffimage_valid_pixels'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='real_bogus_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
