# Generated by Django 2.0.4 on 2021-02-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0062_auto_20200708_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfieldmsb',
            name='active',
            field=models.NullBooleanField(),
        ),
    ]
