# Generated by Django 2.0.4 on 2021-02-06 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0063_surveyfieldmsb_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfield',
            name='targeted_galaxies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyfield',
            name='targeted_transients',
            field=models.ManyToManyField(blank=True, to='YSE_App.Transient'),
        ),
        migrations.AddField(
            model_name='surveyobservation',
            name='msb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YSE_App.SurveyFieldMSB'),
        ),
    ]
