# Generated by Django 3.2.1 on 2021-05-05 22:35
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("YSE_App", "0064_auto_20210206_2001")]

    operations = [
        migrations.AlterField(
            model_name="hostphotdata",
            name="diffim",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hostphotdata",
            name="forced",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hostspectrum",
            name="redshift_quality",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="surveyfield",
            name="active",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="surveyfieldmsb",
            name="active",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transient",
            name="has_chandra",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transient",
            name="has_hst",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transient",
            name="has_spitzer",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transient",
            name="k2_validated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transientdiffimage",
            name="valid_pixels",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transientphotdata",
            name="diffim",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transientphotdata",
            name="discovery_point",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transientphotdata",
            name="forced",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transientspectrum",
            name="redshift_quality",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
