# Generated by Django 3.2.3 on 2021-06-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0065_auto_20210505_2235'),
        ('YSE_App', '0065_host_panstarrs_objid'),
    ]

    operations = [
    ]
