# Generated by Django 3.2.5 on 2021-12-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YSE_App', '0066_merge_20210604_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='alt_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
