name: Build and Push Docker web image

on:
  push:
    branches:
      - develop-dave-docker

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: yse_pz_web
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHRC_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
